# Generated by Django 4.2 on 2023-04-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('cooking_time', models.DurationField()),
                ('difficulty', models.CharField(max_length=50)),
            ],
        ),
    ]
