# Generated by Django 4.2 on 2023-05-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(default='Breakfast', on_delete=django.db.models.deletion.CASCADE, to='recipes.category'),
        ),
    ]
