# Generated by Django 4.2 on 2023-05-17 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_type_remove_recipe_type_recipe_name_recipe_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.type'),
        ),
    ]
