# Generated by Django 4.2 on 2023-05-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_recipe_name_alter_recipe_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='Breakfasts', max_length=255),
        ),
    ]
