# Generated by Django 4.2 on 2023-05-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='type_id',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfasts'), ('Lunch', 'Lunches'), ('Dinner', 'Dinners')], default='Breakfast', max_length=10),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
